version: "3.9"

services:
  frontend:
    image: natalka1122/frontend
    ports:
      - 5000:5000/tcp
    environment:
      BACKEND_URL: http://backend:5000
    networks:
      - backend
      - default

  backend:
    image: natalka1122/backend
    networks:
      - backend

networks:
  backend:
  default:
