version: "3.9"

services:
  frontend:
    # image: nginx
    build:
      context: .
      dockerfile: Dockerfile
      args: frontemd/

  backend:
#    image: nginx
    build:
      context: .
      dockerfile: Dockerfile
      args: backend/
