version: "3.9"

services:
  frontend:
    # image: nginx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_DIR: frontend/

  backend:
#    image: nginx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_DIR: backend/
